import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"]
});

export const metadata: Metadata = {
  title: "Snippy URL",
  description: "Generated by BatDev",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="relative">
      <body className={`${inter.className} ${geistSans.variable} ${geistMono.variable} grid grid-rows-[auto_1fr_auto] min-h-dvh bg-green-body `}>
        <header className="w-full sticky top-0 z-50 bg-neutral-950/0 backdrop-blur-sm py-4">
          <nav className="wrapper">
            <h2 className="text-xl font-bold font-display block hover:text-lime-500"><Link href='/'>Snippy URL</Link></h2>
          </nav>
        </header>



        <main className="w-full grid grid-rows-[1fr-1fr] relative">
          {children}
        </main>


        <footer className="p-4 ">
          ©2025 by batDev64
        </footer>
      </body>
    </html >
  )
}